- src/pheval/post_processing/post_processing.py
Defining dataclasses for bare minimum data required from the tool-specific output and the final ranked result for PhEval standard output.
> #51 define dataclasses required in the tool-specific output for variant and gene prioritisation results (WIP)

- src/pheval/cli_pheval.py
- src/pheval/runners/runner.py
Adding ```version``` option to pheval run command
> 67 add version option to pheval run

- src/pheval/prepare/update_phenopacket.py
- src/pheval/utils/constants.py
- src/pheval/utils/phenopacket_utils.py
- tests/test_phenopacket_utils.py
Added methods to `GeneIdentifierUpdater` class to retrieve the gene symbol from a gene identifier. Also added tests for its functionality. No CLI changes
> 79 obtain the gene symbol from a gene identifier

- resources/custom.Makefile
- src/pheval/cli_pheval_utils.py
- src/pheval/utils/utils.py
- tests/test_utils.py
> fixes Update Makefile to satisfy new semsim scramble/conversion parameters #152

- Makefile
- resources/Makefile.j2
- resources/pheval-config.yaml
> replacing shell pwd by directories.workspace in Makefile j2 template

- src/pheval/config_parser.py
- src/pheval/runners/runner.py
- tests/input_dir/configs/default/config.yaml
- tests/test_runner.py
Adding property to runner for retrieving the `pheval_disease_results` directory and creating if specified in the`config.yaml`
> 162 create pheval disease results directory

- Makefile
- resources/Makefile.j2
- resources/pheval-config.yaml
> 168 fixing phenotype and software symlinks in makefile

- src/pheval/utils/phenopacket_utils.py
Updated the HGNC complete set to 2023-01-07 and renamed (removed date)
> 176 update and rename hgnc complete set in resources

- src/pheval/runners/runner.py
Removed a duplicated pheval_gene_results `mkdir` statement
> removing pheval_gene_results duplicated mkdir statement

- src/pheval/analyse/generate_plots.py
- src/pheval/analyse/generate_summary_outputs.py
- src/pheval/constants.py
Generalised methods used for generating plots. There was a lot of repetition here for generating the gene/variant/disease plots
> 184 generalise methods for generating plots

- src/pheval/analyse/rank_stats.py
- tests/test_generate_plots.py
- tests/test_rank_stats.py
Calculating the summary stats from the total number in the corpus rather than the number found
> 191 calculate percentages in the top top3 top5 from total number in corpus

- resources/Makefile.j2
- resources/pheval-config.yaml
> Makefile multiple PhEval runner tool versions feature

- docs/developing_a_pheval_plugin.md
Updated the documentation for setting up a PhEval plugin. Added a section for PhEval "helper" methods which would be useful to people setting up a runner implementation
> 208 update docs

- src/pheval/prepare/create_noisy_phenopackets.py
Refactored docstrings to Google docstrings
> Refactor docstrings in `create_noisy_phenopackets.py` to Google docstrings

- src/pheval/prepare/create_spiked_vcf.py
refactoring docstrings to Google docstrings
> Refactor docstrings in `create_spiked_vcf.py` to Google docstrings

- src/pheval/prepare/update_phenopacket.py
Refactored docstrings to Google docstrings
> 223 refactor docstrings in update phenopacketpy

- src/pheval/utils/phenopacket_utils.py
- tests/test_phenopacket_utils.py
Refactored docstrings in `phenopacket_utils.py` to Google docstrings.
> 213 refactor docstrings in phenopacket utilspy

- src/pheval/prepare/create_spiked_vcf.py
fixing the formatting of some docstrings and fixing the typing of lists
> Fixing some docstrings in`create_spiked_vcf.py` so it is unified with the others

- src/pheval/analyse/benchmark_generator.py
refactored docstrings to follow Google docstring format
> refactor docstrings in `benchmark_generator.py`

- src/pheval/analyse/benchmarking_data.py
refactoring docstrings to follow google docstring format
> Refactor docstrings in `benchmarking_data.py`

- src/pheval/analyse/disease_prioritisation_analysis.py
refactoring docstrings to follow google docstring format
> Refactor docstrings in `disease_prioritisation_analysis.py`

- src/pheval/analyse/generate_plots.py
Refactor docstrings to follow google docstring format
> 240 refactor docstrings in generate plotspy

- src/pheval/analyse/parse_pheval_result.py
> Refactor docstrings in `parse_pheval_result.py`

- src/pheval/analyse/parse_benchmark_summary.py
> Refactor docstrings in `parse_benchmark_summary.py`

- src/pheval/analyse/prioritisation_rank_recorder.py
> Refactor docstrings in `prioritisation_rank_recorder.py`

- src/pheval/analyse/prioritisation_result_types.py
> Refactor docstrings in `prioritisation_result_types.py`

- src/pheval/analyse/rank_stats.py
> Refactor docstrings in `rank_stats.py`

- src/pheval/analyse/run_data_parser.py
> 255 refactor docstrings in run data parserpy

- src/pheval/analyse/variant_prioritisation_analysis.py
> Refactor docstrings in `variant_prioritisation_analysis.py`

- docs/developing_a_pheval_plugin.md
Updated the link to the cookie cutter template for creating a pheval runner in the docs
> updating the link to the cookie cutter template

- docs/developing_a_pheval_plugin.md
Adding notes for installing the latest version of cruft to avoid project layout naming issues
> Updating docs for developing a pheval plugin with notes about `cruft` installation

- src/pheval/analyse/rank_stats.py
- tests/test_rank_stats.py
Implemented the calculations for precision@k for a run.
It takes the **number of relevant results found at position k** and divides it by the **total number of results at position k**
> 273 calculate precision@k

- src/pheval/cli_pheval_utils.py
> Fixing param name in semsim-to-exomiserdb utils cli command

- src/pheval/analyse/disease_prioritisation_analysis.py
- src/pheval/analyse/gene_prioritisation_analysis.py
- src/pheval/analyse/variant_prioritisation_analysis.py
- src/pheval/cli.py
- src/pheval/cli_pheval.py
- src/pheval/implementations/__init__.py
- src/pheval/prepare/create_spiked_vcf.py
- src/pheval/runners/runner.py
- src/pheval/utils/docs_gen.py
- src/pheval/utils/phenopacket_utils.py
- src/pheval/utils/semsim_utils.py
- src/pheval/utils/utils.py
- tests/test_cli.py
This PR completes [PR 289](https://github.com/monarch-initiative/pheval/pull/289) only fixing tox format issues
>  Fixing param name in semsim-to-exomiserdb utils cli command

- src/pheval/analyse/generate_plots.py
Moved the legend position in the stats plots to the bottom of the plot
> Move legend in stats plot generation

- src/pheval/analyse/analysis.py
Added binary classification stats argument to method
> adding missing argument for writing binary classification stats 

- docs/plugins.md
- mkdocs.yml
Added `plugins.md` listing all pheval plugins
> 308 create pluginsmd

- src/pheval/utils/phenopacket_utils.py
- tests/test_phenopacket_utils.py
Added handling for phenopackets that name chromosomes prefixed with a chr
> 307 add handling of chromosome naming in the phenopacket

- src/pheval/prepare/create_spiked_vcf.py
Replace the sample ID in the VCF in the header lines rather throughout the whole VCF
> Replace sample ID only in VCF header

- src/pheval/post_processing/post_processing.py
- tests/test_post_processing.py
Altered the ranking of the post-processed results so equal ranks are now penalised.
Before:
1,1,3
Now
2,2,3
> 325 alter ranking of results penalising results found at the same rank

- src/pheval/prepare/prepare_corpus.py
Remove phenopackets from final corpus that are do not have any observed phenotypes
> Remove phenopackets with no observed phenotypes

- docs/plugins.md
Updated the documentation with new PhEval runners
> Update documentation with new PhEval runners

- poetry.lock
- pyproject.toml
> Fix the documentation build pipeline

- poetry.lock
- pyproject.toml
Updated PhEval dependencies - error with numpy version.
> 372 update dependencies numpy error

- pyproject.toml
- src/pheval/analyse/generate_plots.py
Replaced infinity values to prevent errors with roc & precision-recall curves
> 379 infinity values create an error with roc curves

- pyproject.toml
- src/pheval/analyse/benchmark_db_manager.py
- src/pheval/analyse/disease_prioritisation_analysis.py
- src/pheval/analyse/gene_prioritisation_analysis.py
- src/pheval/analyse/parse_corpus.py
- src/pheval/analyse/rank_stats.py
- src/pheval/analyse/variant_prioritisation_analysis.py
Enclosed table name in "" in the benchmarking to prevent errors with parsing table names
> 383 duckdbduckdbparserexception parser error syntax error at or near 1

- src/pheval/analyse/benchmark.py
Fixed bug in duplicate rows in the rank comparison reports
> 398-duplicates-in-rank-comparison-reports

- pyproject.toml
- src/pheval/cli_pheval.py
- src/pheval/config_parser.py
- src/pheval/post_processing/post_processing.py
- src/pheval/prepare/create_noisy_phenopackets.py
- src/pheval/prepare/create_spiked_vcf.py
- src/pheval/prepare/prepare_corpus.py
- src/pheval/prepare/update_phenopacket.py
- src/pheval/runners/runner.py
- src/pheval/utils/phenopacket_utils.py
This PR enhances the logging system throughout the `pheval-utils` and `pheval run` commands in **PhEval**, providing more consistent and informative log outputs. The improved logs aim to simplify debugging, increase observability, and offer better insights into execution flows during evaluation runs.
> 402 improve logging throughout codebase

- poetry.lock
- pyproject.toml
- tests/test_cli.py
> bump griffe version

- pyproject.toml
- src/pheval/post_processing/phenopacket_truth_set.py
Fixed merging in the disease results to use `mondo_identifier`
> 424 bugfix with merging disease results in post processing
