src/pheval/analyse/analysis.py, src/pheval/post_processing/post_processing.py, tests/test_analysis.py, tests/test_post_processing.py
These methods include sorting tool-specific output that has been post-processed to the PhEval gene/variant dataclasses in descending order with "best" scores first and assigning ranks to these results.
=> #53 #55  post-processing methods - creation of pheval output

src/pheval/utils/phenopacket_utils.py, tests/test_phenopacket_utils.py
Added method to the `PhenopacketUtil` class to retrieve the sample id for the proband. Also added tests for its functionality. No CLI changes
=> 81 obtain the sample id from a phenopacket

src/pheval/utils/phenopacket_utils.py, tests/test_phenopacket_utils.py
Added a method within the `PhenopacketUtil` class to obtain any phenotypic features marked as excluded. Also added tests to test its functionality. No CLI changes
=> 80 obtain negated phenotypic features from a phenopacket

src/pheval/utils/phenopacket_utils.py, tests/test_phenopacket_utils.py
The `genomicInterpretations` field of a phenopacket can take either a `geneContext` or `variantInterpretation` field. In these cases, the location of where to locate and retrieve the disease causing genes differs.
The method within the`PhenopacketUtil` class that deals with retrieving the genes from a phenopacket has been updated to check if the `variantInterpretation` interpretation field is empty, if it is, retrieve the gene from the `geneContext` otherwise, retrieve from the `variantInterpretation`
=> 91 retrieving genes from interpretations in a phenopacket

src/pheval/post_processing/post_processing.py, tests/test_post_processing.py
Added an additional method `generate_pheval_result()` to be called by the implementor for the final post-processing steps. This method will rank the results and format them into the tsv results depending on whether the implementor provides it with a list of variant or gene results.
Changed public methods to private methods (in the pythonic way) to hopefully document that these should not be called in a runner implementation.
=> 100 merge post processing methods

src/pheval/prepare/create_spiked_vcf.py
When a VCF is spiked with the relevant proband variants the path to the spiked VCF path is added to the phenopacket `Files`. The phenopacket schema requires this to formatted like `file:///path/to/relavant_file` rather than an absolute path. I have just added the `file://` to be prepended to an absolute path. LIRICAL is quite stringent on this being formatted this way and will throw an error for an invalid URI. It is better to change this to be consistent with the phenopacket schema's requirements.
This won't impact any of the CLI or methods called later in the runners as I am ignoring the path provided in the phenopacket and providing the path in the CLI parameters for the tool from the testdata directory.
=> Alter spike vcfs methods to create a valid URI for the phenopacket

src/pheval/post_processing/post_processing.py
Python was not able to recognise the typing of list contents, i.e., `[RankedPhEvalVariantResult]` and so threw errors when called in the runner implementation for post-processing. Fixed this issue by checking that all the items in the list are that of the same class and then writing the corresponding result
=> fixing bug in `generate_pheval_result()`

src/pheval/prepare/create_spiked_vcf.py, src/pheval/utils/phenopacket_utils.py, tests/test_create_spiked_vcf.py, tests/test_phenopacket_utils.py
Added an `info` field to the `ProbandCausativeVariant` data class. This is implemented in the `causative_variants()` method, when the phenopacket variants are retrieved for spiking into the VCF file. This `info` field is now spiked into the VCF record and structural variants are spiked correctly according to the VCF specification e.g., a deletion variant will contain `N` in the `ref` field and `<DEL>` in the `alt` field. Added relevant tests for any new functionality
=> 122 add info variable to probandcausativevariant dataclass

src/pheval/prepare/create_spiked_vcf.py
The URI path written to the phenopacket after spiking the VCF is now decoded before writing. Using the built-in library `urllib` to decode any URL-encoded characters in the path
=> decode encoded characters from uri path

src/pheval/utils/phenopacket_utils.py, tests/test_phenopacket_utils.py
In the `PhenopacketUtil` class and `PhenopacketRebuilder` class, where the file format of the VCF file is either being added/checked/file name taken from the path, these methods looked for files where the file attributes matched `VCF` these needed to be changed to `vcf` for consistency with what is added to the phenopacket after the VCF is spiked as well as what is described in the phenopacket schema documentation
=> changing VCF file format to be expected in file attributes 

src/pheval/analyse/generate_summary_outputs.py
Deleted a `print` statement in `generate_summary_outputs.py` which has most likely been accidentally left in the code when trying to fix a bug in a prior PR
=> delete print statement in `generate_summary_outputs.py`

src/pheval/analyse/generate_summary_outputs.py
The rank comparison file naming was incorrect due to accessing the same tool config directory for naming the output file. Altered by unpacking the tuple containing the ranks/prioritisation results for the specific run to name the file.
=> fix naming of rank comparison file names

src/pheval/prepare/create_spiked_vcf.py, src/pheval/utils/phenopacket_utils.py, tests/test_create_spiked_vcf.py
Fixed the occurrence of a blank `INFO` field in spiked VCF records - this happened because the absence of a value in the phenopacket is not `None` and is instead an empty string
=> fix blank info field in spiked vcf records

src/pheval/analyse/analysis.py, src/pheval/analyse/generate_plots.py, src/pheval/analyse/generate_summary_outputs.py, src/pheval/utils/phenopacket_utils.py, tests/test_analysis.py, tests/test_generate_plots.py, tests/test_phenopacket_utils.py
Implemented methods to assess the performance of disease prioritisation, i.e., this could be used to benchmark the performance of OntoGPT, however, once all the runners have been set up to be able to output this result type, this could result in the comparison of Exomiser vs OntoGPT vs LIRICAL. Apologies for the larger PR, I think this was probably unavoidable.
1. `analysis.py` -> Ultimately where all the analysis for disease prioritisation is happening, i.e., iterating over the pheval disease results and checking if the known disease in the phenopacket is found in the results and recording the summary stats.
2. `generate_plots.py` -> Methods implemented for generating the disease summary plots.
3. `generate_summary_outputs.py` -> Methods implemented for generating disease summary …
=> 165 implement support within analysis methods for disease matching

src/pheval/analyse/generate_summary_outputs.py
Generalised methods in the `RankComparisonGenerator` class
=> 186 generalise rankcomparisongenerator class

src/pheval/analyse/prioritisation_rank_recorder.py, tests/test_analysis.py, tests/test_generate_summary_outputs.py
Changed variant separators from `_` to `-` when reporting variant results in the benchmarking
=> change variant separators from `_` to `-`

src/pheval/analyse/benchmarking_data.py, src/pheval/analyse/generate_plots.py, src/pheval/analyse/parse_benchmark_summary.py, src/pheval/analyse/rank_stats.py, src/pheval/cli.py, src/pheval/cli_pheval_utils.py, tests/test_generate_plots.py, tests/test_rank_stats.py
Implemented a command to generate a stats bar plot from the summary benchmark TSV output from the `benchmark` or `benchmark-comparison` command. This allows further customisation to the plot output, there is specification for a title and the summary TSV `results_directory_path` column values can be altered to provide a more specific run identifier.
=> 199 add command to generate stats plot

src/pheval/utils/file_utils.py
Refactored docstrings in `file_utils.py` to Google docstrings
=> 217 refactor docstrings in file utilspy

src/pheval/post_processing/post_processing.py
Refactoring docstrings for classes and functions in `post_processing.py` to follow google docstring fornatting
=> Refactor docstrings in `post_processing.py`

src/pheval/cli_pheval_utils.py
Changed the default plot type that comes out the benchmarking command to the cumulative bar. 
The labels on the plot will show 'Top, Top3, Top5, Top10'
=> changing default plot type to cumulative bar

src/pheval/post_processing/post_processing.py
Added a check in the post-processing methods that will print a warning message if there are no results found. This should stop the error @souzadevinicius was getting in his experiments and write out the rest of the results without stopping the entire process.
=> implement handling of empty results

src/pheval/post_processing/post_processing.py
Change `pass` to `return` statement in function. Before, if the result was empty it would continue to try and generate a result - the `return` will exit out of the function to avoid this happening
=> Handle empty results

src/pheval/analyse/generate_summary_outputs.py, tests/test_generate_summary_outputs.py
Changed the `rank_decrease` column to `rank_change` in the rank comparison summary file. In cases where a result is not found this has been replaced by a `GAINED` or `LOST` label.
e.g.,
```tsv
Phenopacket	Gene	exomiser-13.3.0-2109/lirical-default/pheval_gene_results	GPT-4_turbo/complex_prompt/pheval_gene_results	rank_change
1	Abdul_Wahab-2016-GCDH-Patient_5.json	GCDH	1	1.0	0.0
2	Ajmal-2013-BBS1-IV-5_family_A.json	BBS1	3	0.0	LOST
3	Al-Dosari-2010-TFAP2A-10-year-old_girl.json	TFAP2A	0	66	GAINED
4	Al-Hashmi-2018-SNX14-IV-1.json	SNX14	9	6	-3
```
=> 300 change rank decrease to rank change in rank comparison summary

src/pheval/analyse/binary_classification_stats.py, src/pheval/analyse/generate_plots.py, tests/test_analysis.py, tests/test_binary_classification_stats.py
Added methods for generating ROC curves and precision-recall curves from the binary classification stats during the benchmarking
=> 302 add roc curves and precision recall curves to benchmarking output

src/pheval/cli_pheval_utils.py, src/pheval/prepare/create_spiked_vcf.py, tests/test_create_spiked_vcf.py
Added separate `--hg19-template-vcf` and `--hg38-template-vcf` arguments to the spike vcf command. This allows a corpus of phenopackets with mixed assemblies to be spiked into vcfs.
There is also a refactoring of the methods so that each VCF (if specified) is only read and parsed once during the workflow - this is to improve efficiency and cut down the time taken to carry out the command.
=> 313 add option for hg19 and hg38 vcf for spiking command

src/pheval/analyse/generate_plots.py
Added a boolean flag for the `generate-stats-plot` command to specify whether the plots are generated from the TSV file or not. This will bypass the creation of the ROC & precision-recall curves which isn't possible with the TSV and will throw an error.
=> add flag for `generate-stats-plot` for creation from TSV

src/pheval/cli.py, src/pheval/cli_pheval_utils.py, src/pheval/prepare/create_spiked_vcf.py, src/pheval/prepare/prepare_corpus.py, src/pheval/prepare/update_phenopacket.py, src/pheval/utils/phenopacket_utils.py, tests/test_phenopacket_utils.py
Implemented a `prepare-corpus` command.
A user can specify if they intend to carry out variant, gene, and/or disease analysis with their prepared corpus. The command will check the corpora and ensure that all required fields in the phenopacket are filled (required for matching results to known entities in the benchmarking). When a phenopacket is removed from the final corpus a warning message is logged, informing of the phenopacket that was removed.
There is also the option of spiking VCF with variant information from a phenopacket and updating the gene identifiers.
For example, to prepare the phenopacket-store corpus for our use (variant analysis only) we would use the command:
```bash
pheval-utils prepare-corpus --phenopacket-dir /path/to/phenopacket-store --gene-identifier ensembl_id …
```
=> 311 implement a prepare corpus command

src/pheval/prepare/create_spiked_vcf.py, tests/test_create_spiked_vcf.py
If a variant entry position cannot be found for spiking a variant into a template VCF an Index error is thrown. For example, if the phenopacket has a variant on chrX, and there are no records of chrX variants in the VCF, then the index error is thrown. To overcome this, just add the variant to the end of the file and write a logger warning
=> Handle IndexError for spiking variants into a VCF

src/pheval/post_processing/post_processing.py
Fixed the type checking in the extracted results - checks if all the instances in the list are that of `PhEvalDiseaseResult`/`PhEvalVariantResult`/`PhEvalGeneResult`.
=> Fix type checking in extracted results

src/pheval/analyse/disease_prioritisation_analysis.py, src/pheval/analyse/gene_prioritisation_analysis.py, src/pheval/analyse/parse_pheval_result.py, src/pheval/analyse/variant_prioritisation_analysis.py, src/pheval/utils/file_utils.py
Currently, we iterate over the PhEval TSV processed output --> find the corresponding phenopacket in the test data directory --> benchmark this way.
This change will instead, iterate over the phenopackets in the test data directory --> find the corresponding PhEval TSV output (if none found this is handled) --> benchmark this way
This will allow us to account for missing results, i.e., if a tool fails on certain results no output is written then this is accounted in the new way of benchmarking
=> 331 iterate over corpus directory and check for corresponding results when benchmarking

src/pheval/cli_pheval_utils.py, src/pheval/prepare/create_spiked_vcf.py, src/pheval/prepare/prepare_corpus.py
Add arguments for specifying a directory of hg19 or hg38 VCFs to spike variants in for the spike VCFs command.
No changes to code structure - just now adding the option to iterate through a directory of VCFs and select one at random for each phenopacket to spike the variant in. This should help with problems in benchmarking with the same background VCF for all samples
=> 317 add arguments hg19 vcf dir and hg38 vcf dir to spike vcf command

src/pheval/analyse/variant_prioritisation_analysis.py, src/pheval/utils/phenopacket_utils.py
The variants may be read in as strings/integers for the position - which may result in a failed match for different types. Now chromosomes are explicitly str and position int
=> Ensure type matching in benchmark for variants

src/pheval/analyse/gene_prioritisation_analysis.py, src/pheval/post_processing/post_processing.py, tests/test_analysis.py
Some tools may output alternate gene identifiers/symbols for the same top-ranked variant (AI-MARRVEL as an example).
To allow for this, the post-processing has now allowed for either a single gene symbol/identifiers or a list of gene symbols/identifiers - this avoids breaking the other runners.
The benchmarking code for the gene analysis has also been altered - processing either a list of gene symbols/gene identifiers or a single one to match against the causative gene(s)
=> 333 allow multiple genes/gene identifiers for a single ranked result

src/pheval/analyse/gene_prioritisation_analysis.py
This will fix/prevent this error:
```
File "/nfs/production/parkinso/spot/pheval/monarch_pheval_zenodo/.venv/lib/python3.10/site-packages/pheval/analyse/gene_prioritisation_analysis.py", line 158, in _check_string_representation
if list_pattern.match(entity):
TypeError: expected string or bytes-like object
make[2]: *** [Makefile:256: results/gene_rank_stats.svg] Error 1
make[1]: *** [Makefile:515: pheval] Error 2
make: *** [Makefile:521: all] Error 2
```
=> Ensure string typing when checking for string/list in gene prioritisation analysis

src/pheval/cli_pheval_utils.py, src/pheval/prepare/create_noisy_phenopackets.py
Allows the specification of hp.obo/hp.json etc etc to be consumed by OAK and used in the workflow for scrambling phenopackets in place of fetching remotely
=> Added an option to the scramble phenopackets command to allow for a local cached ontology file

src/pheval/analyse/assess_prioritisation_base.py, src/pheval/analyse/disease_prioritisation_analysis.py, src/pheval/analyse/gene_prioritisation_analysis.py, src/pheval/analyse/variant_prioritisation_analysis.py, tests/test_analysis.py
Removed the duplicated methods/code found in `gene_prioritisation_analysis.py`, `variant_prioritisation_analysis.py`, and `gene_prioritisation_analysis.py`.
The duplicated methods were extracted into a common base class and so inherited in the new subclasses.
=> 357 remove duplicated code in variant/gene/disease analysis

src/pheval/analyse/generate_summary_outputs.py
The column names to be dropped were being passed to the DuckDB statement as a single string, this fix ensures they are separate strings contained in a tuple
=> Fix error in dropping columns in benchmarking db

docs/pipeline.md
=> Update PhEval Pipeline Documentation

src/pheval/prepare/prepare_corpus.py, src/pheval/utils/phenopacket_utils.py, tests/test_phenopacket_utils.py
Added a check in the `prepare-corpus` command that will check whether the reference and alternate allele in the variants for a phenopacket are identical or not. If they are identical the phenopacket is removed from the final corpus.
=> 370 add check for ref and alt alleles for variants recorded in a phenopacket

src/pheval/analyse/disease_prioritisation_analysis.py, src/pheval/analyse/gene_prioritisation_analysis.py, src/pheval/analyse/variant_prioritisation_analysis.py, tests/test_analysis.py
Adds handling if a PhEval TSV result file is not found for a corresponding phenopacket. 
Some tools generate an empty raw results file or don't generate results at all when it fails for a sample - added handling to support this.
=> 375 error when a pheval result cannot be found

src/pheval/analyse/benchmark_db_manager.py
Replaced possible NaN values with None so that benchmarking can be completed successfully. This sometimes occurs with the mapping to ENSEMBL identifiers.
=> NaN values interrupt the benchmarking

pyproject.toml, src/pheval/prepare/prepare_corpus.py
An error is thrown if a phenopacket already exists at the destination directory during the prepare corpus command. Added handling for the copying of a phenopacket
=> 381 prepare corpus copy error

docs/developing_a_pheval_plugin.md, src/pheval/post_processing/post_processing.py, tests/test_post_processing.py
This introduces enhanced ranking functionality to handle compound heterozygous variants in PhEval results through a new `grouping_id` parameter. The grouping_id allows variants that contribute collectively to a phenotype (e.g., compound heterozygous variants within the same gene) to be ranked together (and not penalised), ensuring their combined effect is accurately represented in the analysis. If variants are not compound heterzygous, they will be ranked with the default method.
If a `grouping_id` is not specified the code will **not** break, it will just default to the current method of ranking variants - this is important as not all VGPAs will give an idea of whether a variant is compound het or not and so they can just dismiss this.
=> 363 account for compound het variants

pyproject.toml, src/pheval/analyse/benchmark.py, src/pheval/analyse/run_data_parser.py
Added early validation checks to the benchmarking yaml file (checking if results directory paths do exist) and a check for whether the duckdb database exists before any heavy computation. Prior the errors would arise but much later in the process. This allows for quicker debugging.
=> 420 add early validation for inputoutput paths before running benchmarking steps
